version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: skillswap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mongo:
    image: mongo:7-jammy
    container_name: skillswap-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
